# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install dev tools
        run: |
          pip install pytest mypy black isort

      - name: Run tests
        run: |
          pytest tests/

      - name: Type checking with mypy
        run: |
          mypy stnlib/

      - name: Linting with black and isort
        run: |
          black --check stnlib/ tests/
          isort --check-only stnlib/ tests/

      - name: Generate documentation (optional)
        run: |
          pip install pdoc
          pdoc --html stnlib
        if: always()